#!/bin/bash

# Together, these options tell gcc to compile the source code into an optimized object file with debugging information included. The resulting object file can then be linked with other object files and libraries to create an executable program.
gcc -g -O -c *.c
# gcc -c *.c